In [8]:
import numpy as np

## how to create a vector

v1 = np.array([1, 3, 5, 7, 9, 11])
v2 = np.array([2, 4, 6, 8, 10, 12])

print(f"Vector 1: {v1}")
print(f"Vector 2: {v2}")

## how to add vectors

v_add = v1 + v2
v_subtract = v1 - v2

print(f"v1+v2 = {v_add}")
print(f"v1-v2 = {v_subtract}")

Vector 1: [ 1  3  5  7  9 11]
Vector 2: [ 2  4  6  8 10 12]
v1+v2 = [ 3  7 11 15 19 23]
v1-v2 = [-1 -1 -1 -1 -1 -1]


In [9]:
## how to scale vectors

scalar = 2
v_scaled = scalar * v1
print(f"v1 * scalar = {v_scaled}")

v1 * scalar = [ 2  6 10 14 18 22]


In [10]:
## how to dot vectors

dot_product = np.dot(v1, v2)
print(f"dot product v1, v2 = {dot_product}")

dot product v1, v2 = 322


In [14]:
## Norm of a vector

magnitude_v1 = np.linalg.norm(v1)
print(f"v1 norm is = {magnitude_v1:.4f}")

v1 norm is = 16.9115


In [18]:
## multi dimensional array

A = np.array([[1, 2, 3], [4, 5, 6]])
print(A)
print()
B = np.array([[7, 8, 9], [10, 11, 12], [13, 14, 15]])
print(B)

[[1 2 3]
 [4 5 6]]

[[ 7  8  9]
 [10 11 12]
 [13 14 15]]


In [19]:
## adding matricies

C = np.array([[1, 2, 3], [4, 5, 6,]])
matrix_add = A + C
matrix_subtract = A - C
print(f"matrixA + matrixC = {matrix_add}")
print(f"matrixA - matrixC = {matrix_subtract}")

matrixA + matrixC = [[ 2  4  6]
 [ 8 10 12]]
matrixA - matrixC = [[0 0 0]
 [0 0 0]]


In [20]:
## multiplying matricies

matrix_mul = np.dot(A, B)
print(f"matrixA * matrixB = {matrix_mul}")

matrixA * matrixB = [[ 66  72  78]
 [156 171 186]]


In [21]:
## Transposing

transpose_A = A.T
print(f"Transpose_A = {transpose_A}")

Transpose_A = [[1 4]
 [2 5]
 [3 6]]


In [24]:
## solving matricies
A = np.array([[2, 3], [4, -1]])
b = np.array([5, 3])
print(A)
print(B)
x = np.linalg.solve(A, b)
print(x)

[[ 2  3]
 [ 4 -1]]
[[ 7  8  9]
 [10 11 12]
 [13 14 15]]
[1. 1.]


In [29]:
## eiganvalues and eiganvectors

A = np.array([[2, 1], [1, 2]])
e_value, e_vector = np.linalg.eig(A)
print(f"eiganvalue and eiganvector = {e_value}, {e_vector}")

eiganvalue and eiganvector = [3. 1.], [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [32]:
A = np.array([[4, 7], [2, 6]])
A_inv = np.linalg.inv(A)

print(A)
print(f"A_inverse = {A_inv}")

[[4 7]
 [2 6]]
A_inverse = [[ 0.6 -0.7]
 [-0.2  0.4]]


In [33]:
## identity matrix

identity = np.dot(A, A_inv)
print(identity)

[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
